name = "smasnugdevelopment"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
[vars]
NODE_VERSION = "22"
NEXT_PUBLIC_POSTHOG_KEY = "phc_DL6MniRm5eI4p0cZjVjQvAHNTc3fJKfdpWGwQyfRVeR"
NEXT_PUBLIC_POSTHOG_HOST = "https://us.i.posthog.com"
