import type { Metadata } from "next";
import { Roboto_Mono, Baskervville } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Footer } from "@/components/footer";
import { PostHogProvider } from "@/components/PostHogProvider";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
});

const boringLegalFont = Baskervville({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-boring-legal",
});

export const metadata: Metadata = {
  title: "Smasnug Development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${robotoMono.className} ${boringLegalFont.variable} antialiased min-h-screen flex flex-col`}
      >
        <PostHogProvider>
          <ThemeProvider attribute="class" forcedTheme="dark">
            <Navbar />
            <main className="mb-auto">{children}</main>
            <Footer />
          </ThemeProvider>
        </PostHogProvider>
      </body>
    </html>
  );
}
